import type { Metadata } from 'next'
import { Geist, Geist_Mono, Nunito_Sans } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import AppHeader from '@/components/headers/app-header'
import { Providers } from '@/components/providers'
import SearchBar from '@/components/search-bar'

const nunitoSans = Nunito_Sans({ variable: '--font-sans' })

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className={nunitoSans.variable} lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex min-h-screen w-full flex-col items-center gap-8 bg-background p-4 md:p-10">
					<Providers>
						<AppHeader />
						<SearchBar />
						{children}
						<Toaster />
					</Providers>
				</div>
			</body>
		</html>
	)
}
